const WHATSAPP_API_VERSION = process.env.WHATSAPP_API_VERSION || "v22.0";
const WHATSAPP_PHONE_NUMBER_ID = process.env.WHATSAPP_PHONE_NUMBER_ID || "992950697232409";
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN || "EAAQQtZBTUcLYBQ2QNyPJX2ZAhLcD1c1JoRjVNjLKva5Wkg70YDRNuzS8JqyDSF5TCTlKPFprg9oPWu2WZBHOUqfMbSuOjsnEDvxbwMSTcRB8A7qCr7SSMvIAHvUSQkX0PoU2fyRSIW3eGSDxwf1u1efpEiHUuFsGZCHqrzsY1HstklOf9WizyRS7pygzZByIv3bRBv8xwqMn7wCJMjnERZBtmZBZAQZBnhKZBmTejRNEMq7yxt4agOl0fp5hrNMTE0HTGxt08UJDsGuFeZA7J04bntbT1sVmAZDZDD";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";

module.exports = {
    WHATSAPP_API_VERSION,
    WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_TOKEN,
    OPENAI_API_KEY
};
