const WHATSAPP_API_VERSION = process.env.WHATSAPP_API_VERSION || "v17.0";
const WHATSAPP_PHONE_NUMBER_ID = process.env.WHATSAPP_PHONE_NUMBER_ID || "117721278011867";
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN || "YOUR_WHATSAPP_TOKEN";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";

module.exports = {
    WHATSAPP_API_VERSION,
    WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_TOKEN,
    OPENAI_API_KEY
};
