const WHATSAPP_API_VERSION = process.env.WHATSAPP_API_VERSION || "v22.0";
const WHATSAPP_PHONE_NUMBER_ID = process.env.WHATSAPP_PHONE_NUMBER_ID || "992950697232409";
const WHATSAPP_TOKEN = process.env.WHATSAPP_TOKEN || "EAAQQtZBTUcLYBQ6iZAFdCjA0z6ZAD0TvAuHT56UxIrR0nFJ5ezSnFZAspONhZCCF9e4pci6d1TwTUw1vDYZCbyEoqPvprKKpK1eYrV0q5B7K5qsTFNm5BaP76T4JH1Cij7ZB0E2dZA42RDRJMd3Cq3dKUZCZC34KoNCpmfuo1UXhoKKFF2eDzG9lUUUGx1KbjlstZCABe8fTJYWg8dhY0aaKBPdCFgwrNsdCKXWCgCPtr1Y4JGaTX5e2D0iKj7njZBvKRJBfmqQaa3vZCOWulLY0YZCEq8Hft9";
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";

module.exports = {
    WHATSAPP_API_VERSION,
    WHATSAPP_PHONE_NUMBER_ID,
    WHATSAPP_TOKEN,
    OPENAI_API_KEY
};
